### ISSUE TITLE
`spec/and` precludes coercion

### ISSUE THREAD

**Issue by vemv** [wilkerlucio/spec-coerce#29]
Hi,

I found out that `spec/and` appears to preclude coercion:

```clj
(spec/def ::foo (spec/and any? integer?))

(spec-coerce/coerce `integer? "42") ;; does its job correctly: returns the number 42

(spec-coerce/coerce ::foo "42")     ;; returns the string "42"
```

WDYT?

Thanks - Victor

**Comment by wilkerlucio** [comment]
Hello, this follows the same conventions for spec regarding generators, it uses the first option you give, in your example, the first option is `any?`, because of that, there is no coercion.

So, this tries to work for the most general case, that is having on the first, if you have a special case you can use the custom coerce registry to explicitly define the coercer.

Makes sense?

**Comment by vemv** [comment]
> Hello, this follows the same conventions for spec regarding generators, it uses the first option you give, in your example, the first option is any?, because of that, there is no coercion.

Thanks for the clarification, I wasn't aware of this convention or that it was applied here for coercion.

Armed with this knowledge I'm able to move on now.

Still, have the suspicion that a `spec/and` can be translated to something smart, like a transformation analog to `->`:

```clj
(spec/and string? lowercase?) ;; gets translated to (pseudocode): `(-> x coerce-to-string coerce-to-lowercase)
```

However I'm happy to leave that just as an idea without a specific desire for it be implemented.

**Comment by vemv** [comment]
Btw, the convention is indeed mentioned in README:

```
; Like spec generators, when using `and` it will use the first item as the inference source
```

However I might not be necessarily compelled to re-read the examples whenever I encounter an issue. Maybe a `Caveats` section would help.
